services:
  mysql:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password --sql-mode="NO_ENGINE_SUBSTITUTION" --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mensa
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./docker/mysql/schemas:/docker-entrypoint-initdb.d
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD,"
      start_period: 60s
      start_interval: 1s
      timeout: 5s
      retries: 3
      interval: 30s
